version: '3.7'
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -connectRetries=10 migrate
    volumes:
      - ./db/conf:/flyway/conf
      - ./db/sql:/flyway/sql
    depends_on:
      - db
  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_DB=postgres
    ports:
      - 32770:5432
